name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Code Checkout
      uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        
    - name: Setup NPM
      uses: actions/npm@v2.0.0
      
    - name: Step Into Project Dir
      run: cd HADotNet.CommandCenter
      
    - name: npm install
      run: npm install
      
    - name: Step Out Of Project Dir
      run: cd ..
        
    - name: Build with dotnet
      run: dotnet build --configuration Release
